id = "moonbit-lab"
name = "MoonBit Lab"
description = "Native MoonBit language support for Zed, developed as a provenance-aware thin client."
version = "0.2.9"
schema_version = 1
authors = ["PL Playground"]
repository = "https://github.com/kokoro-aya/playgrounds"
capabilities = []

[grammars.moonbit]
repository = "https://github.com/moonbitlang/tree-sitter-moonbit"
rev = "5435c307c6cf2ef0d508a99047b06f35a4308444"

[lib]
kind = "Rust"
version = "0.7.0"
